### ISSUE TITLE
Cursor drops to next line on initial emoticon add in FireFox

### ISSUE THREAD

**Issue by cyphix333** [samclarke/SCEditor#393]
Not a big issue but thought I would report it.

I have noticed that say if you haven't entered any content into the editor and you use the emoticon toolbar option to add a smiley it will add the smiley and drop the cursor to the next line in FireFox (36.0).

However it appears it isn't _really_ on the next line as if you type any text or add another smiley it will appear on the same line as the initial smiley.

If you use "Backspace" to get rid of the initial smiley then it works as it should.

I tested it in Chrome and didn't notice this behaviour.

**Comment by brunoais** [comment]
First thing that gets to my mind is that it may be caused by the fake `<br>` tag that firefox works with...

**Comment by brunoais** [comment]
@samclarke What do you think this might be?

**Comment by samclarke** [comment]
It's a bug with Firefox and it's selection handling which happens when the editor hasn't had focus before.

The `autofocus()` function already fixes it though so it should be possible to add a check which will call the `autofocus()` function when `focus()` is called if the editor hasn't had focus before.

**Comment by samclarke** [comment]
I've investigated this a bit more and what's happening is Firefox is putting the focus at the start of the body element before any children, including the first paragraph.

Because of that the emoticon image is inserted before the paragraph and, because of what looks like a FF bug, the cursor is then shown as if it is in the first paragraph when it isn't.

The `autofocus()` function places the cursor at the correct position so using that for the initial focus should fix it.

**Comment by samclarke** [comment]
Thanks for reporting. It should be fixed in 1.4.7 when it's released.

**Comment by cyphix333** [comment]
I've finally just updated to 1.4.7 and noticed this still occurs; at least for me on FF 38.0.5.

**Comment by samclarke** [comment]
This has now been fixed by 768e85fc37e60530664dfd0776e7bd8273a25545
